name = "MCMCDiagnostics"
uuid = "c03f26be-b9c8-4f7f-b41c-4dec83eed245"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.4.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"
StatsBase = "0.33"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
