name = "MCMCDiagnostics"
uuid = "c03f26be-b9c8-4f7f-b41c-4dec83eed245"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.4.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
